# Generated by Django 5.1 on 2024-08-23 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('weekend', 'Weekend Pricing'), ('seasonal', 'Seasonal Pricing'), ('holiday', 'Holiday Pricing')], max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('price_modifier', models.DecimalField(decimal_places=2, help_text='e.g., 1.5 for 50% increase, 0.8 for 20% discount', max_digits=5)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='properties.property')),
            ],
        ),
    ]
