# Generated by Django 5.1 on 2024-08-23 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_pricingrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingrule',
            name='price_modifier',
            field=models.DecimalField(decimal_places=2, help_text='Enter a percentage. E.g., 150 for 50% increase, 80 for 20% discount', max_digits=5),
        ),
    ]
