# Generated by Django 5.1 on 2024-08-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_pricingrule_price_modifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingrule',
            name='price_modifier',
            field=models.DecimalField(decimal_places=2, help_text='Enter a percentage. E.g., 120 for 20% increase, 80 for 20% discount', max_digits=5),
        ),
    ]
