# Generated by Django 5.1 on 2024-08-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_pricingrule_price_modifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingrule',
            name='rule_type',
            field=models.CharField(choices=[('weekend', 'Weekend Pricing'), ('seasonal', 'Seasonal Pricing'), ('override', 'Override Pricing')], max_length=10),
        ),
    ]
