# Generated by Django 5.1 on 2024-08-23 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_pricingrule_rule_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('no_checkin', 'No Check-in'), ('no_checkout', 'No Check-out'), ('min_stay', 'Minimum Stay'), ('min_stay_period', 'Minimum Stay for Period'), ('gap_override', 'Gap Stay Override')], max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('days_of_week', models.CharField(blank=True, help_text='Comma-separated list of day numbers (0=Monday, 6=Sunday)', max_length=7)),
                ('min_nights', models.PositiveIntegerField(blank=True, null=True)),
                ('max_nights', models.PositiveIntegerField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_rules', to='properties.property')),
            ],
            options={
                'ordering': ['property', 'rule_type', 'start_date'],
            },
        ),
    ]
