# Generated by Django 5.1 on 2024-08-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_bookingrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='allow_gap_stays',
            field=models.BooleanField(default=True, help_text='Allow bookings shorter than the minimum stay to fill gaps between bookings'),
        ),
    ]
