# Generated by Django 5.1 on 2024-08-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_property_allow_gap_stays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingrule',
            name='days_of_week',
        ),
        migrations.RemoveField(
            model_name='bookingrule',
            name='max_nights',
        ),
        migrations.AddField(
            model_name='property',
            name='no_checkin_days',
            field=models.CharField(blank=True, help_text='Days when check-in is not allowed', max_length=7),
        ),
        migrations.AddField(
            model_name='property',
            name='no_checkout_days',
            field=models.CharField(blank=True, help_text='Days when check-out is not allowed', max_length=7),
        ),
        migrations.AlterField(
            model_name='bookingrule',
            name='rule_type',
            field=models.CharField(choices=[('min_stay', 'Minimum Stay'), ('min_stay_period', 'Minimum Stay for Period')], max_length=20),
        ),
    ]
