# Generated by Django 5.1 on 2024-08-23 21:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_remove_bookingrule_days_of_week_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingrule',
            options={'ordering': ['property', 'start_date']},
        ),
        migrations.RemoveField(
            model_name='bookingrule',
            name='rule_type',
        ),
        migrations.AddField(
            model_name='property',
            name='minimum_stay',
            field=models.PositiveIntegerField(default=1, help_text='Minimum number of nights required for a booking'),
        ),
        migrations.AlterField(
            model_name='bookingrule',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingrule',
            name='min_nights',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingrule',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
