# Generated by Django 5.1 on 2024-08-23 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_total_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['check_in_date'], 'verbose_name_plural': 'Bookings'},
        ),
    ]
